server:
  port: 80
spring:
  resources:
    static-locations: classpath:/img/,classpath:/static/
  #配置数据库数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

#MyBatis映射配置文件没有放在Mapper包下而是放在Resources目录下时的配置
#mybatis:
  #扫描classpath中mapper目录下的映射配置文件
#  mapper-locations: classpath:/mapper/*.xml
  #别名配置。使用pojo时可以直接使用pojo的类型不用加包名
#  type-aliases-package: cn.smart.pojo


  thymeleaf:
    prefix: classpath:/templates/thymeleaf/
    suffix: .html
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML

