server:
  port: 80
spring:
  mvc:
    view:
      prefix: /WEB_INF/JSP/
      suffix: .jsp
  activemq:
    broker-url: tcp://192.168.66.186:61616
    user: "admin"
    password: "admin"
    #是否使用内置MQ
    in-memory: false
    #是否使用连接池，每发送一条数据创建一个连接
    pool:
      enabled: true
      #链接池最大连接数
      max-connections: 10
    #空闲的连接过期时间，默认为30秒
      idle-timeout: 30000
      #强制的连接过期时间，与idleTimeout的区别在于：idleTimeout是在连接空闲一段时间失效，而expiryTimeout不管当前连接的情况，只要达到指定时间就失效。默认为0，never
    #      expiry-timeout: 0
    #配置又缓存的ConnectionFactory,session的缓存大小定制
    #指定跳过包检查
    packages:
      trusted: cn.smart
  jms:
    cache:
      session-cache-size: 3
    template:
      #默认队列
      default-destination: test-spring
    pub-sub-domain: true
